resources:

- name: code-repo-dct-dev
  type: git
  check_every: 1m
  source: &code-repo-cache-dct
    uri: git@github.homedepot.com:SupplyChain-IPR/iom-dct-apps.git
    branch: development
    private_key: ((github-private-key))


- name: repo-cache-dct
  type: gradle-cache
  check_every: 1m
  source:
    <<: *code-repo-cache-dct
    paths:
      - build.gradle
      - gradle.properties

- name: ci
  type: git
  source:
    uri: git@github.homedepot.com:ci-cd/concourse-common.git
    branch: master
    private_key: ((github-private-key))
  check_every: 24h

- name: repo-cache-dct-npm
  type: npm-cache
  source:
    <<: *code-repo-cache-dct
    project-path: iom-ui
    registry: https://npm.artifactory.homedepot.com/artifactory/api/npm/npm/

- name: ci-iom
  type: git
  source:
    uri: git@github.homedepot.com:SupplyChain-IPR/IOMServices_CICD.git
    branch: master
    private_key: ((github-private-key))
  check_every: 30m

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
  check_every: 24h

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      registry_mirror: https://docker.artifactory.homedepot.com

  - name: gradle-cache
    type: docker-image
    source:
      repository: docker.artifactory.homedepot.com/concourse/gradle-cache-resource
      tag: latest
      registry_mirror: https://docker.artifactory.homedepot.com

  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest


groups:
 - name: IOM BG TEST
   jobs:
   - Version DEV
   - Deploy DEV Services
   - Deploy DEV UI


jobs:
- name: Version DEV
  serial: true
  max_in_flight: 1
  plan:
  - get: code-repo-dct-dev
    trigger: true
  - get: ci
  - task: Version and Tag
    file: ci/concourse/github_version_and_tag.yml
    input_mapping: {code-repo: code-repo-dct-dev}
    params:
      ENVIRONMENT: development 
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      TRACKER_TOKEN: ((tracker-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
    on_failure:
      put: slack
      params:
        channel: ((slack-channel))
        username: ((slack-username))
        icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
        text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed versioning! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"

- name: Deploy DEV Services
  serial: true
  max_in_flight: 1
  plan:
  - get: code-repo-dct-dev
    trigger: true
    passed: [Version DEV]
  - get: ci
  - get: ci-iom
  - get: repo-cache-dct
  - task: build
    file: ci/concourse/gradle_build.yml
    input_mapping: {code-repo: code-repo-dct-dev, repo-cache: repo-cache-dct}
    params:
      GRADLE_USER_HOME: ../repo-cache/.gradle
      DIST_DIRECTORY: build/libs
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployservice
          SQH_JOB_NAME: ARTIFACT
          SQH_STATUS: FAILED
          ENVIRONMENT: dev
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed building! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
  - task: SQH Started
    file: ci/concourse/sqh.yml
    input_mapping: {code-repo: code-repo-dct-dev}
    params:
      SQH_BUILD_NAME: pcf-deployservice
      SQH_JOB_NAME: DEPLOY-DEV
      SQH_STATUS: STARTED
      ENVIRONMENT: development
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      TRACKER_TOKEN: ((tracker-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      token: ((qualityhub-token-dct))
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployservice
          SQH_JOB_NAME: DEPLOY-DEV
          SQH_STATUS: FAILED
          ENVIRONMENT: development
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed communicating with SQ Hub! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
  - task: deploy
    file: ci-iom/concourse/cloud_foundry_deploy_llc.yml
    input_mapping: {code-repo: code-repo-dct-dev , deploy-repo: dist , ci: ci-iom}
    params:
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      ENVIRONMENT: perf
      DEPLOYMENT_USER: ((deployment-user))
      DEPLOYMENT_PWD: ((deployment-pwd))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      CF_API: ((cf-api-dev))
      CF_ORG: ((cf-org-dev))
      CF_SPACE: ((cf-space-perf))
      DEPLOY_TYPE: SERVICES
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployservice
          SQH_JOB_NAME: DEPLOY-DEV
          SQH_STATUS: FAILED
          ENVIRONMENT: development
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed deploying to PCF! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
  - task: SQH Completed
    file: ci/concourse/sqh.yml
    input_mapping: {code-repo: code-repo-dct-dev}
    params:
      SQH_BUILD_NAME: pcf-deployservice
      SQH_JOB_NAME: DEPLOY-DEV
      SQH_STATUS: COMPLETED
      ENVIRONMENT: development
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      TRACKER_TOKEN: ((tracker-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      token: ((qualityhub-token-dct))
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployservice
          SQH_JOB_NAME: DEPLOY-DEV
          SQH_STATUS: FAILED
          ENVIRONMENT: development #TODO: use the appropriate environment name from your buildConfig that matches
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          #TODO replace below channel name with your channel
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed communicating with SQ Hub! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
- name: Deploy DEV UI
  serial: true
  max_in_flight: 1
  plan:
  - get: code-repo-dct-dev
    trigger: true
    passed: [Version DEV]
  - get: ci
  - get: ci-iom
  - get: repo-cache-dct-npm
  - task: SQH Started
    file: ci/concourse/sqh.yml
    input_mapping: {code-repo: code-repo-dct-dev}
    params:
      SQH_BUILD_NAME: pcf-deployui
      SQH_JOB_NAME: DEPLOY-DEV
      SQH_STATUS: STARTED
      ENVIRONMENT: development
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      TRACKER_TOKEN: ((tracker-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      token: ((qualityhub-token-dct))
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployui
          SQH_JOB_NAME: DEPLOY-DEV
          SQH_STATUS: FAILED
          ENVIRONMENT: development
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed communicating with SQ Hub! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
  - task: build
    file: ci-iom/concourse/yarn_build.yml
    input_mapping: { code-repo: code-repo-dct-dev, repo-cache: repo-cache-dct-npm , ci: ci-iom }
    params:
      GRADLE_USER_HOME: ../repo-cache/.gradle
      DIST_DIRECTORY: dist
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      BUILD_TARGET: develop
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployui
          SQH_JOB_NAME: ARTIFACT
          SQH_STATUS: FAILED
          ENVIRONMENT: dev
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed building! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
  - task: deploy
    file: ci-iom/concourse/cloud_foundry_deploy_llc.yml
    input_mapping: { code-repo: code-repo-dct-dev , deploy-repo: dist , ci: ci-iom }
    params:
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      ENVIRONMENT: perf
      DEPLOYMENT_USER: ((deployment-user))
      DEPLOYMENT_PWD: ((deployment-pwd))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      CF_API: ((cf-api-dev))
      CF_ORG: ((cf-org-dev))
      CF_SPACE: ((cf-space-perf))
      DEPLOY_TYPE: UI
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployui
          SQH_JOB_NAME: DEPLOY-DEV
          SQH_STATUS: FAILED
          ENVIRONMENT: development
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed deploying to PCF! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"
  - task: SQH Completed
    file: ci/concourse/sqh.yml
    input_mapping: {code-repo: code-repo-dct-dev}
    params:
      SQH_BUILD_NAME: pcf-deployui
      SQH_JOB_NAME: DEPLOY-DEV
      SQH_STATUS: COMPLETED
      ENVIRONMENT: development
      GITHUB_PRIVATE_KEY: ((github-private-key))
      GITHUB_TOKEN: ((github-token))
      TRACKER_TOKEN: ((tracker-token))
      SLACK_WEBHOOK_URL: ((slack-webhook-url))
      token: ((qualityhub-token-dct))
    on_failure:
      aggregate:
      - task: SQH fail
        file: ci/concourse/sqh.yml
        input_mapping:
          code-repo: code-repo-dct-dev
          test-results: test
        params:
          SQH_BUILD_NAME: pcf-deployui
          SQH_JOB_NAME: DEPLOY-DEV
          SQH_STATUS: FAILED
          ENVIRONMENT: development #TODO: use the appropriate environment name from your buildConfig that matches
          GITHUB_PRIVATE_KEY: ((github-private-key))
          GITHUB_TOKEN: ((github-token))
          TRACKER_TOKEN: ((tracker-token))
          SLACK_WEBHOOK_URL: ((slack-webhook-url))
          token: ((qualityhub-token-dct))
      - put: slack
        params:
          #TODO replace below channel name with your channel
          channel: ((slack-channel))
          username: ((slack-username))
          icon_url: https://avatars1.githubusercontent.com/u/7809479?v=3&s=200
          text: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME failed communicating with SQ Hub! <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|  Click for details.>"

